title: "Daniel"
description: "Just to feel something"
about: "A place for human thoughts"
location: "Berlin, Deutschland"
email: your-email@example.com
baseurl: ""
url: "https://strazzulla.github.io/kusa/" # replace by your site's url
twitter_username: strazzulla
github_username:  strazzulla

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md